zomato_clone-master/zomato_clone-master/reviewer/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from reviewer import views

urlpatterns = [
  path('', views.Index.as_view(), name = 'index'),
  path('restaurant/<int:pk>', views.Restaurant.as_view(), name = 'restaurant'),
  path('restaurant/<int:pk>/add_review', views.AddReview.as_view(), name = 'restaurant_review'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zomato_clone-master/zomato_clone-master/zomato/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviewer.urls'))
]

zomato_clone-master/zomato_clone-master/reviewer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import (
  MinValueValidator,
  MaxValueValidator
)

# Create your models here.
class Restaurant(models.Model):
  name = models.CharField(max_length = 256)
  address = models.TextField()
  veg_only = models.BooleanField(default = False)

  def __str__(self):
    return self.name

class Review(models.Model):
  user = models.ForeignKey(User, on_delete = models.CASCADE)
  restaurant = models.ForeignKey('Restaurant', on_delete = models.CASCADE)
  title = models.CharField(max_length = 256)
  stars = models.IntegerField(validators = [MaxValueValidator(5), MinValueValidator(0)])
  body = models.TextField()
  # img = models.ImageField(upload_to='media', default='face4.jpg')

  def __str__(self):
    return self.title

zomato_clone-master/zomato_clone-master/reviewer/forms.py
from django import forms

from reviewer import models

class ReviewForm(forms.ModelForm):
  class Meta:
    model = models.Review
    fields = ['title', 'body', 'stars']

zomato_clone-master/zomato_clone-master/reviewer/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import (
  ListView,
  DetailView,
  CreateView,
  View
)
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from reviewer import models, forms

# Create your views here.
# @method_decorator(login_required, name='dispatch')
class Index(ListView):
  model = models.Restaurant
  template_name = 'index.html'

class Restaurant(DetailView):
  model = models.Restaurant
  template_name = 'restaurant.html'

class AddReview(CreateView):
  model = models.Review
  fields = ['title', 'body', 'stars']
  template_name = 'review.html'

  def get_success_url(self):
    return '/restaurant/{}'.format(self.kwargs['pk'])

  def form_valid(self, form):
    """If the form is valid, save the associated model."""
    restaurant = models.Restaurant.objects.get(pk = self.kwargs['pk'])
    user = self.request.user
    review = form.save(commit = False)
    review.restaurant = restaurant
    review.user = user
    review.save()
    self.object = review
    return super().form_valid(form)


@login_required
def add_review(request, pk):
  restaurant = models.Restaurant.objects.get(pk = pk)
  review_form = forms.ReviewForm()

  if request.method == "POST":
    review_form = forms.ReviewForm(request.POST)

    if review_form.is_valid():
      # models.Review.objects.create(
      #   user = request.user,
      #   restaurant = restaurant,
      #   title = review_form.cleaned_data['title'],
      #   stars = review_form.cleaned_data['stars'],
      #   body = review_form.cleaned_data['body']
      # )
      review = review_form.save(commit = False)
      review.user = request.user
      review.restaurant = restaurant
      review.save()
      return HttpResponseRedirect('/restaurant/{}'.format(restaurant.id))

  context = {
    "restaurant": restaurant,
    "form": review_form
  }
  return render(request, 'review.html', context)

zomato_clone-master/zomato_clone-master/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
        <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    {% block head %} {% endblock %}
  </head>
  <body>

  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'index' %}">Home</a></li>


      </ul>
    </div>
  </nav>
    {% block content %} {% endblock %}
  </body>
</html>

zomato_clone-master/zomato_clone-master/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
      <h1>Welcome to Zomato</h1><hr>
      <ul>
        {% for restaurant in restaurant_list %}
          <li>
            <a href="{% url 'restaurant' restaurant.id %}">
              {{ restaurant }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>


{% endblock %}

zomato_clone-master/zomato_clone-master/templates/restaurant.html
{% extends 'base.html' %}

{% block content %}

  <h1>Welcome to Zomato</h1>

  <h2>{{ restaurant.name }}</h2>

  <p>
    {{ restaurant.address }}
  </p>

  {% if restaurant.veg_only %}
    green
  {% else %}
    red
  {% endif %}

  <h4>Reviews</h4>

  <ul>
    {% for review in restaurant.review_set.all %}
      <li>{{ review.title }}</li>
      <!-- <img src="{{ review.img.url }}" alt=""> -->
    {% endfor %}
  </ul>

{% endblock %}

zomato_clone-master/zomato_clone-master/templates/review.html
{% extends 'base.html' %}

{% block content %}

  <h1>Add review for {{ restaurant.name }}</h1>

  <form action="" method="post">

    {% csrf_token %}

    {{ form }}

    <button type="submit">
      Submit
    </button>
  </form>

{% endblock %}